// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDlzSlWvlVLGeVFaehrZe-3MB6JMBvrP0',
    appId: '1:714119315861:web:df83da2e40fd8c8a13b69c',
    messagingSenderId: '714119315861',
    projectId: 'matrimony-app-c680d',
    authDomain: 'matrimony-app-c680d.firebaseapp.com',
    databaseURL: 'https://matrimony-app-c680d-default-rtdb.firebaseio.com',
    storageBucket: 'matrimony-app-c680d.firebasestorage.app',
    measurementId: 'G-L8MNHXGH7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhAm47SXJ0_LYvq3y-ux2D0_jvy9OCzYM',
    appId: '1:714119315861:android:55c28d297ee53a1e13b69c',
    messagingSenderId: '714119315861',
    projectId: 'matrimony-app-c680d',
    databaseURL: 'https://matrimony-app-c680d-default-rtdb.firebaseio.com',
    storageBucket: 'matrimony-app-c680d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhzRxMJYz_xM9PDwQYEZYYBYgwRGs3zqQ',
    appId: '1:714119315861:ios:8fb7e16ab175b6b713b69c',
    messagingSenderId: '714119315861',
    projectId: 'matrimony-app-c680d',
    databaseURL: 'https://matrimony-app-c680d-default-rtdb.firebaseio.com',
    storageBucket: 'matrimony-app-c680d.firebasestorage.app',
    iosBundleId: 'com.blessedunion.app.matrimonyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhzRxMJYz_xM9PDwQYEZYYBYgwRGs3zqQ',
    appId: '1:714119315861:ios:8fb7e16ab175b6b713b69c',
    messagingSenderId: '714119315861',
    projectId: 'matrimony-app-c680d',
    databaseURL: 'https://matrimony-app-c680d-default-rtdb.firebaseio.com',
    storageBucket: 'matrimony-app-c680d.firebasestorage.app',
    iosBundleId: 'com.blessedunion.app.matrimonyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDlzSlWvlVLGeVFaehrZe-3MB6JMBvrP0',
    appId: '1:714119315861:web:cf8d62db7725941613b69c',
    messagingSenderId: '714119315861',
    projectId: 'matrimony-app-c680d',
    authDomain: 'matrimony-app-c680d.firebaseapp.com',
    databaseURL: 'https://matrimony-app-c680d-default-rtdb.firebaseio.com',
    storageBucket: 'matrimony-app-c680d.firebasestorage.app',
    measurementId: 'G-K2WE0Q9EMR',
  );
}
