name: matrimony_app
description: "MATRIMONY - ADARSH PRADEEP"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.0

  # UI & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4

  # Networking & Media
  http: ^1.2.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/background_image.jpg
    - assets/images/male_2.png
