import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'pages/home_page.dart'; // You can change this to landingPage.dart if needed
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with proper platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MatrimonyApp());
}

class MatrimonyApp extends StatelessWidget {
  const MatrimonyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Matrimony App',
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Colors.pink, // Feel free to customize
      ),
      home: const HomePage(), // or WelcomePage(), LandingPage(), etc.
    );
  }
}
